live_config_reload = true
working_directory = "None"

[shell]
program = "/bin/fish"
args = ["-l"]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#1d2235"
blue = "#338fff"
cyan = "#00eff0"
green = "#efef00"
magenta = "#00eff0"
red = "#ff5f5f"
white = "#989898"
yellow = "#efef00"

[colors.cursor]
cursor = "#005e8b"
text = "#bfefff"

[colors.normal]
black = "#000000"
blue = "#2fafff"
cyan = "#00d3d0"
green = "#44bc44"
magenta = "#feacd0"
red = "#ff5f50"
white = "#ffffff"
yellow = "#d0bc00"

[colors.primary]
background = "#0d0e1c"
foreground = "#ffffff"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 13.0

[font.bold]
family = "Moralerspace Neon HWNF"

[font.bold_italic]
family = "Moralerspace Neon HWNF"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Moralerspace Neon HWNF"

[font.normal]
family = "Moralerspace Neon HWNF"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
