live_config_reload = true
working_directory = "None"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "/bin/bash"
args = ["-l"]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#1d2235"
blue = "#338fff"
cyan = "#00eff0"
green = "#44df44"
magenta = "#ff66ff"
red = "#ff5f5f"
white = "#989898"
yellow = "#efef00"

[colors.cursor]
cursor = "#005e8b"
text = "#bfefff"

[colors.normal]
black = "#000000"
blue = "#2fafff"
cyan = "#00d3d0"
green = "#44bc44"
magenta = "#feacd0"
red = "#ff5f59"
white = "#ffffff"
yellow = "#d0bc00"

[colors.primary]
background = "#0d0e1c"
foreground = "#ffffff"
dim_foreground = "#989898"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 13.0

[font.bold]
family = "Moralerspace Neon HWNF"

[font.bold_italic]
family = "Moralerspace Neon HWNF"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Moralerspace Neon HWNF"

[font.normal]
family = "Moralerspace Neon HWNF"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[keyboard]
bindings = [
   { key = "A",         mods = "Alt",       chars = "\u001ba"                       },
   { key = "B",         mods = "Alt",       chars = "\u001bb"                       },
   { key = "C",         mods = "Alt",       chars = "\u001bc"                       },
   { key = "D",         mods = "Alt",       chars = "\u001bd"                       },
   { key = "E",         mods = "Alt",       chars = "\u001be"                       },
   { key = "F",         mods = "Alt",       chars = "\u001bf"                       },
   { key = "G",         mods = "Alt",       chars = "\u001bg"                       },
   { key = "H",         mods = "Alt",       chars = "\u001bh"                       },
   { key = "I",         mods = "Alt",       chars = "\u001bi"                       },
   { key = "J",         mods = "Alt",       chars = "\u001bj"                       },
   { key = "K",         mods = "Alt",       chars = "\u001bk"                       },
   { key = "L",         mods = "Alt",       chars = "\u001bl"                       },
   { key = "M",         mods = "Alt",       chars = "\u001bm"                       },
   { key = "N",         mods = "Alt",       chars = "\u001bn"                       },
   { key = "O",         mods = "Alt",       chars = "\u001bo"                       },
   { key = "P",         mods = "Alt",       chars = "\u001bp"                       },
   { key = "Q",         mods = "Alt",       chars = "\u001bq"                       },
   { key = "R",         mods = "Alt",       chars = "\u001br"                       },
   { key = "S",         mods = "Alt",       chars = "\u001bs"                       },
   { key = "T",         mods = "Alt",       chars = "\u001bt"                       },
   { key = "U",         mods = "Alt",       chars = "\u001bu"                       },
   { key = "V",         mods = "Alt",       chars = "\u001bv"                       },
   { key = "W",         mods = "Alt",       chars = "\u001bw"                       },
   { key = "X",         mods = "Alt",       chars = "\u001bx"                       },
   { key = "Y",         mods = "Alt",       chars = "\u001by"                       },
   { key = "Z",         mods = "Alt",       chars = "\u001bz"                       },
   { key = "A",         mods = "Alt|Shift", chars = "\u001bA"                       },
   { key = "B",         mods = "Alt|Shift", chars = "\u001bB"                       },
   { key = "C",         mods = "Alt|Shift", chars = "\u001bC"                       },
   { key = "D",         mods = "Alt|Shift", chars = "\u001bD"                       },
   { key = "E",         mods = "Alt|Shift", chars = "\u001bE"                       },
   { key = "F",         mods = "Alt|Shift", chars = "\u001bF"                       },
   { key = "G",         mods = "Alt|Shift", chars = "\u001bG"                       },
   { key = "H",         mods = "Alt|Shift", chars = "\u001bH"                       },
   { key = "I",         mods = "Alt|Shift", chars = "\u001bI"                       },
   { key = "J",         mods = "Alt|Shift", chars = "\u001bJ"                       },
   { key = "K",         mods = "Alt|Shift", chars = "\u001bK"                       },
   { key = "L",         mods = "Alt|Shift", chars = "\u001bL"                       },
   { key = "M",         mods = "Alt|Shift", chars = "\u001bM"                       },
   { key = "N",         mods = "Alt|Shift", chars = "\u001bN"                       },
   { key = "O",         mods = "Alt|Shift", chars = "\u001bO"                       },
   { key = "P",         mods = "Alt|Shift", chars = "\u001bP"                       },
   { key = "Q",         mods = "Alt|Shift", chars = "\u001bQ"                       },
   { key = "R",         mods = "Alt|Shift", chars = "\u001bR"                       },
   { key = "S",         mods = "Alt|Shift", chars = "\u001bS"                       },
   { key = "T",         mods = "Alt|Shift", chars = "\u001bT"                       },
   { key = "U",         mods = "Alt|Shift", chars = "\u001bU"                       },
   { key = "V",         mods = "Alt|Shift", chars = "\u001bV"                       },
   { key = "W",         mods = "Alt|Shift", chars = "\u001bW"                       },
   { key = "X",         mods = "Alt|Shift", chars = "\u001bX"                       },
   { key = "Y",         mods = "Alt|Shift", chars = "\u001bY"                       },
   { key = "Z",         mods = "Alt|Shift", chars = "\u001bZ"                       },
   { key = "Key1",      mods = "Alt",       chars = "\u001b1"                       },
   { key = "Key2",      mods = "Alt",       chars = "\u001b2"                       },
   { key = "Key3",      mods = "Alt",       chars = "\u001b3"                       },
   { key = "Key4",      mods = "Alt",       chars = "\u001b4"                       },
   { key = "Key5",      mods = "Alt",       chars = "\u001b5"                       },
   { key = "Key6",      mods = "Alt",       chars = "\u001b6"                       },
   { key = "Key7",      mods = "Alt",       chars = "\u001b7"                       },
   { key = "Key8",      mods = "Alt",       chars = "\u001b8"                       },
   { key = "Key9",      mods = "Alt",       chars = "\u001b9"                       },
   { key = "Key0",      mods = "Alt",       chars = "\u001b0"                       },
]


[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
