#!/bin/sh

# Layout configuration
yashiki layout-set-default tatami
yashiki set-outer-gap 10  # Gap between windows and screen edges (global)

# Cursor warp (mouse follows focus)
yashiki set-cursor-warp on-focus-change

# Not use default mode
yashiki declare-mode base
yashiki bind alt-slash enter-mode base
yashiki bind --mode base alt-slash enter-mode normal

# Tag bindings (tag N = bitmask $((1<<(N-1))))
for i in 1 2 3 4 5 6 7 8 9; do
  yashiki bind --mode base "$i" tag-view "$((1<<(i-1)))"
  yashiki bind --mode base "shift-$i" window-move-to-tag "$((1<<(i-1)))"
  yashiki bind --mode base "ctrl-$i" tag-toggle "$((1<<(i-1)))"
done

# Window focus
yashiki bind --mode base j window-focus down
yashiki bind --mode base k window-focus up
yashiki bind --mode base h window-focus left
yashiki bind --mode base l window-focus right

yashiki bind --mode base n window-toggle-float

# swap mastar
yashiki bind --mode base m layout-cmd zoom

# Multi-monitor
yashiki bind --mode base ctrl-h output-send prev
yashiki bind --mode base ctrl-l output-send next

# suppress some popup behaviors
yashiki rule-add --subrole Dialog float
yashiki rule-add --subrole FloatingWindow float
yashiki rule-add --subrole other ignore

## Emacs child frame behavior
yashiki rule-add --app-id org.gnu.Emacs --close-button none ignore
